### ISSUE TITLE
Division By Zero Error Not Happening

### ISSUE THREAD

**Issue by elliottderosa** [ELLDER054/gizmo-lang#12]
The parser needs to check if the value of the sides is zero while parsing division expressions.
It also needs to be smart enough to know identifier's values. This should report an error.

```
int a = 5;
int b = 0;
write(a / b);
```

**Comment by freetink3r** [comment]
If it makes you feel any better, even gcc and clang won't issue any warnings about your sample code, even when compiling with -Wdiv-by-zero. They _will_, however, warn you about:
```
int a = 5;
write (a / 0);
```
