### ISSUE TITLE
[Suggestion] Too many commits

### ISSUE THREAD

**Issue by sharkbait2** [ELLDER054/gizmo-lang#14]
Hi, just here to give you a friendly suggestion that apparently you have a lots of tiny commits for every single tiny changes.

Just use [`git commit --amend`](https://www.atlassian.com/git/tutorials/rewriting-history) to override the last commit with the new changes.

Have a nice day!

**Comment by elliottderosa** [comment]
Thanks for the suggestion! I'll try it out.
