### ISSUE TITLE
Calling functions with no arguments gives error

### ISSUE THREAD

**Issue by elliottderosa** [ELLDER054/gizmo-lang#17]
Calling a function with no arguments like this:

```
int a() {
    return 5;
}
write(a());
```

results in this error.

```
error: On line 4
Unexpected token
write(a());
        ^
```
The cause of this problem is that our parser does not allow expressions to be empty.
The parser expects an expression right after the left parenthesis, but instead finds a right parenthesis. It then throws the error above.

**Comment by janetannderosa** [comment]
### _

> Wow!

_ This is awesome the way you worded this error!

Calling a function with no arguments like this:

int a() {
    return 5;
}write(a());  
**RESULTS IN AN ERROR.**

error: On line 4
Unexpected token
write(a())
        ^
GOOD JOB, ELLIOTT!
