### ISSUE TITLE
Allow optional 'else-if' continuations after 'if' statements

### ISSUE THREAD

**Issue by elliottderosa** [ELLDER054/gizmo-lang#19]
Else-if statements in Gizmo look like this for now:
```
if true or false {
    \ do something
} else if false {
    \ do something else
}
```
Though they **are** subject to change.

**Comment by janetannderosa** [comment]
First of all, it is really cool that I could just click on #19 in your email and come to this sight and see this "issue." Here are 2 questions for you: "Am I correct in calling 'Allow optional 'else-if' continuations after 'if' statements' an issue?  One other question "Is 'Tokens with a length that overflows the token buffer size need to be handled' also considered one of your Gizmo issues?"
