### ISSUE TITLE
[Question] How to contribute?

### ISSUE THREAD

**Issue by sharkbait2** [ELLDER054/gizmo-lang#20]
Hi, I don't have quite experience with LLVM, I'm thinking about contributing here. Also I want to learn how LLVM works, Is it a frame work that you've integrate or is it a toolchain? Any pointers would be helpful. And just wondering what are the ways I could contribute without code?

**Comment by elliottderosa** [comment]
"LLVM is a compiler and a toolkit for building compilers. The LLVM project is a collection of modular and reusable compiler and toolchain technologies. LLVM helps build new computer languages and improve existing languages." One way to contribute is to test different programs in Gizmo and try to break it. Or you could help with documentation.
