### ISSUE TITLE
Indexing for expressions

### ISSUE THREAD

**Issue by elliottderosa** [ELLDER054/gizmo-lang#22]
Indexes are defined as "an identifier followed by a left bracket followed by an expression followed by a right bracket".
If we could replace the identifier with an expression, we could support things like this:

```
var = list[index][index]
```
or:

```
var = ("abc" + "def")[0]
```

**Comment by janetannderosa** [comment]
Ohhhh that would be cool and very helpful if you could replace the identifier with an expression ... is this a possibility?

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: ELLDER054 ***@***.***>
Sent: Tuesday, June 29, 2021 2:22:54 PM
To: ELLDER054/gizmo-lang ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ELLDER054/gizmo-lang] Indexing for expressions (#22)

[[***CAUTION*** This email originated from outside of Messiah University]]

Indexes are defined as an identifier followed by a left bracket followed by an expression, finally followed by a right bracket.
If we could replace the identifier with an expression, we could support things like this:

var = list[index][index]


or:

var = ("abc" + "def")[0]

**Comment by elliottderosa** [comment]
It would be a possibility, though it will be difficult to get right.
