### ISSUE TITLE
Indexes when assigning

### ISSUE THREAD

**Issue by elliottderosa** [ELLDER054/gizmo-lang#23]
Assignments need to be able to support:

```
list[5] = something
```
Do to the fact that an assignment is defined as "an identifier followed by the equals sign followed by an expression", this is not allowed.

**Comment by janetannderosa** [comment]
Just curious why this is not allowed... Is the problem with the = sign or with the "something?"

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: ELLDER054 ***@***.***>
Sent: Tuesday, June 29, 2021 2:24:45 PM
To: ELLDER054/gizmo-lang ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ELLDER054/gizmo-lang] Indexes when assigning (#23)

[[***CAUTION*** This email originated from outside of Messiah University]]

Assignments need to be able to support:

list[5] = something


Do to the fact that an assignment is defined as "an identifier followed by the equals sign followed by an expression", this is not allowed.

**Comment by elliottderosa** [comment]
Gizmo doesn’t know that the user is allowed to do the
list[5] part

**Comment by janetannderosa** [comment]
Ohhhhh... Can you send Gizmo an email and tell him... LOL.. only kidding.😂

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
